# Please run `docker-compose up` command and request to localhost:3000 in browser.
version: '1.000'

services:

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: protfolio

    express:
        image: node:17-alpine
        restart: always
        command: sh -c "npm install && npm start"
        depends_on:
            - "mongo"
        ports:
            - '4000:4000'
        working_dir: /app
        volumes:
            - ./backend:/app
        environment:
            - MONGO_URI=mongodb://root:password@mongo:27017/?authSource=admin
            - PORT=4000
            - ORIGIN=http://localhost:3000

    react:
        image: node:17-alpine
        restart: always
        command: sh -c "npm install && npm start"
        depends_on:
            - "express"
        ports:
            - '3000:3000'
        working_dir: /app
        volumes:
            - ./frontend:/app
        environment:
            - SERVER=http://localhost:4000
